#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

if [ ! -f ${OPENSHIFT_DATA_DIR}.magento-sample-installed ];
then
  cd $OPENSHIFT_GEAR_DIR

  echo "Poulating database"
  mysql --socket=${OPENSHIFT_DB_SOCKET} -u${OPENSHIFT_DB_USERNAME} -p${OPENSHIFT_DB_PASSWORD} ${OPENSHIFT_APP_NAME} < ${OPENSHIFT_TMP_DIR}magento-sample-data-1.6.1.0/magento_sample_data_for_1.6.1.0.sql

  echo "Generating Magento admin password"
  # Generate the admin password
  MD5STR=$(head -1024 /dev/urandom | md5sum | md5sum)
  MAGENTO_ADMIN_PASSWORD="${MD5STR:2:8}"
  echo "Magento admin password: $MAGENTO_ADMIN_PASSWORD"

  echo "Configuring Magento for first use"
  php -f ${OPENSHIFT_REPO_DIR}php/install.php -- \
    --license_agreement_accepted "yes" \
    --locale "en_GB" \
    --timezone "Europe/London" \
    --default_currency "GBP" \
    --db_host "$OPENSHIFT_DB_HOST" \
    --db_name "$OPENSHIFT_APP_NAME" \
    --db_user "$OPENSHIFT_DB_USERNAME" \
    --db_pass "$OPENSHIFT_DB_PASSWORD" \
    --skip_url_validation \
    --url "http://$OPENSHIFT_APP_DNS" \
    --use_rewrites "yes" \
    --use_secure "yes" \
    --enable_charts \
    --secure_base_url "https://$OPENSHIFT_APP_DNS" \
    --use_secure_admin "yes" \
    --admin_firstname "NetSrv" \
    --admin_lastname "Consulting" \
    --admin_email "enquires@netsrv-consulting.com" \
    --admin_username "admin" \
    --admin_password "$MAGENTO_ADMIN_PASSWORD"

  # Set the flag
  touch $OPENSHIFT_DATA_DIR/.magento-sample-installed
fi

# Rehome the configuration to 
if [ -f "${OPENSHIFT_REPO_DIR}php/app/etc/local.xml" ]; then
  mv ${OPENSHIFT_REPO_DIR}php/app/etc/local.xml ${OPENSHIFT_DATA_DIR}
fi
ln -s ${OPENSHIFT_DATA_DIR}local.xml ${OPENSHIFT_REPO_DIR}php/app/etc/local.xml

# Reindex DB
php ${OPENSHIFT_REPO_DIR}php/shell/indexer.php reindexall
